name: Automated Jio Hotstar JSON Updater

on:
  schedule:
    - cron: '*/7 * * * *' 
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Data and Log
        run: |
          curl -sS -o jiotv.json "https://raw.githubusercontent.com/fakeall12398-sketch/JIO_TV/refs/heads/main/full_channels.json"
          
          export TZ="Asia/Kolkata"
          echo "ðŸš€ JioHotstar Synced BY Sayan | IST: $(date +'%Y-%m-%d %H:%M:%S') | ID: $RANDOM" >> jio_status.txt

      - name: Configure Git User
        run: |
          git config --global user.email "kajju3864@gmail.com"
          git config --global user.name "kajju027"

      - name: Commit and Push
        run: |
          export TZ="Asia/Kolkata"
          git add jiotv.json jio_status.txt
          git commit -m "JioHotstar DB & Log Updated âœ… [$(date +'%d-%m-%Y %H:%M')]" --allow-empty
          git push
          
