name: Automated Jio Hotstar JSON Updater

on:
  schedule:
    - cron: '*/7 * * * *' 
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Jio Hotstar JSON
        run: |
          curl -sS -o full_channels.json "https://raw.githubusercontent.com/fakeall12398-sketch/JIO_TV/refs/heads/main/full_channels.json"

      - name: Configure Git User
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Check for Changes
        id: git_status
        run: |
          # Robust check: Detects smallest changes and new files
          if [ -z "$(git status --porcelain)" ]; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Commit and Push
        if: steps.git_status.outputs.has_changes == 'true'
        run: |
          git add full_channels.json
          git commit -m "(SAYAN) Jio Hotstar Letest Update Now Live âœ…ðŸ”¥"
          git push
          
